/*
 XCTestManifests.swift

 This source file is part of the SDGCornerstone open source project.
 https://sdggiesbrecht.github.io/SDGCornerstone

 Copyright ©2019 Jeremy David Giesbrecht and the SDGCornerstone project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

#if !canImport(ObjectiveC)
import XCTest

extension SDGCollationAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCollationAPITests = [
        ("testCoding", testCoding),
        ("testCollationOrder", testCollationOrder),
        ("testInterspersion", testInterspersion),
    ]
}

extension SDGCollationLanguageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCollationLanguageTests = [
        ("testBosnian", testBosnian),
        ("testEnglish", testEnglish),
        ("testFrench", testFrench),
        ("testGerman", testGerman),
        ("testGreek", testGreek),
        ("testHebrew", testHebrew),
        ("testItalian", testItalian),
        ("testSpanish", testSpanish),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGCollationAPITests.__allTests__SDGCollationAPITests),
        testCase(SDGCollationLanguageTests.__allTests__SDGCollationLanguageTests),
    ]
}
#endif
