#if !canImport(ObjectiveC)
import XCTest

extension SDGCollationAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCollationAPITests = [
        ("testCoding", testCoding),
        ("testCollationOrder", testCollationOrder),
        ("testInterspersion", testInterspersion),
    ]
}

extension SDGCollationLanguageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCollationLanguageTests = [
        ("testBosnian", testBosnian),
        ("testEnglish", testEnglish),
        ("testFrench", testFrench),
        ("testGerman", testGerman),
        ("testGreek", testGreek),
        ("testHebrew", testHebrew),
        ("testItalian", testItalian),
        ("testSpanish", testSpanish),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGCollationAPITests.__allTests__SDGCollationAPITests),
        testCase(SDGCollationLanguageTests.__allTests__SDGCollationLanguageTests),
    ]
}
#endif
