# .travis.yml
#
# This source file is part of the SDGCornerstone open source project.
# https://sdggiesbrecht.github.io/SDGCornerstone
#
# Copyright ©2017–2019 Jeremy David Giesbrecht and the SDGCornerstone project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:
    - name: "macOS"
      os: osx
      osx_image: xcode11
      script:
        - "swift test"
    - name: "Linux"
      os: linux
      dist: xenial
      script:
        - "export SWIFT_VERSION=5.1"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "swift test"
    - name: "iOS"
      os: osx
      osx_image: xcode11
      language: objective-c
      xcode_sdk: iphonesimulator
      script:
        - "xcodebuild test -destination 'name=iPhone 11' -scheme SDGCornerstone-Package"
    - name: "watchOS"
      os: osx
      osx_image: xcode11
      script:
        - "swift package generate-xcodeproj"
        - "xcodebuild build -sdk watchos -scheme SDGCornerstone-Package > /dev/null"
    - name: "tvOS"
      os: osx
      osx_image: xcode11
      language: objective-c
      xcode_sdk: appletvsimulator
      script:
        - "xcodebuild test -destination 'name=Apple TV 4K' -scheme SDGCornerstone-Package"
