# .travis.yml
#
# This source file is part of the SDGCornerstone open source project.
# https://sdggiesbrecht.github.io/SDGCornerstone/SDGCornerstone
#
# Copyright ©2017–2018 Jeremy David Giesbrecht and the SDGCornerstone project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

language: generic
matrix:
  include:
    - os: osx
      env:
        - JOB="macOS + Swift Package Manager"
      osx_image: xcode10
      script:
        - "swift test"
    - os: osx
      env:
        - JOB="macOS + Xcode"
      osx_image: xcode10
      script:
        - "swift package generate-xcodeproj"
        - "xcodebuild test -sdk macosx -scheme SDGCornerstone-Package"
    - os: linux
      env:
        - JOB="Linux"
      dist: trusty
      script:
        - "export SWIFT_VERSION=4.2"
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "swift test"
    - os: osx
      env:
        - JOB="iOS"
      osx_image: xcode10
      language: objective-c
      xcode_sdk: iphonesimulator
      script:
        - "swift package generate-xcodeproj"
        - "xcodebuild test -destination 'name=iPhone 8' -scheme SDGCornerstone-Package"
    - os: osx
      env:
        - JOB="watchOS"
      osx_image: xcode10
      script:
        - "swift package generate-xcodeproj"
        - "xcodebuild build -sdk watchos -scheme SDGCornerstone-Package"
    - os: osx
      env:
        - JOB="tvOS"
      osx_image: xcode10
      language: objective-c
      xcode_sdk: appletvsimulator
      script:
        - "swift package generate-xcodeproj"
        - "xcodebuild test -destination 'name=Apple TV 4K' -scheme SDGCornerstone-Package"

cache:
  directories:
  - $HOME/Library/Caches/ca.solideogloria.Workspace
  - $HOME/.cache/ca.solideogloria.Workspace
