/*
 XCTestManifests.swift

 This source file is part of the SDGCornerstone open source project.
 https://sdggiesbrecht.github.io/SDGCornerstone

 Copyright ©2019 Jeremy David Giesbrecht and the SDGCornerstone project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

#if !canImport(ObjectiveC)
import XCTest

extension SDGPersistenceAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPersistenceAPITests = [
        ("testFileConvertible", testFileConvertible),
        ("testFileManager", testFileManager),
        ("testLosslessStringConvertible", testLosslessStringConvertible),
        ("testPreferences", testPreferences),
        ("testSpecification", testSpecification),
        ("testURL", testURL),
    ]
}

extension SDGPersistenceRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPersistenceRegressionTests = [
        ("testCachePermissions", testCachePermissions),
        ("testPercentEncodingIsNotDoubled", testPercentEncodingIsNotDoubled),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGPersistenceAPITests.__allTests__SDGPersistenceAPITests),
        testCase(SDGPersistenceRegressionTests.__allTests__SDGPersistenceRegressionTests),
    ]
}
#endif
