#if !canImport(ObjectiveC)
import XCTest

extension SDGPersistenceAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPersistenceAPITests = [
        ("testFileConvertible", testFileConvertible),
        ("testFileManager", testFileManager),
        ("testLosslessStringConvertible", testLosslessStringConvertible),
        ("testPreferences", testPreferences),
        ("testSpecification", testSpecification),
        ("testURL", testURL),
    ]
}

extension SDGPersistenceRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPersistenceRegressionTests = [
        ("testCachePermissions", testCachePermissions),
        ("testPercentEncodingIsNotDoubled", testPercentEncodingIsNotDoubled),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGPersistenceAPITests.__allTests__SDGPersistenceAPITests),
        testCase(SDGPersistenceRegressionTests.__allTests__SDGPersistenceRegressionTests),
    ]
}
#endif
