/*
 XCTestManifests.swift

 This source file is part of the SDGCornerstone open source project.
 https://sdggiesbrecht.github.io/SDGCornerstone

 Copyright ©2019 Jeremy David Giesbrecht and the SDGCornerstone project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

#if !canImport(ObjectiveC)
import XCTest

extension SDGPrecisionMathematicsAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPrecisionMathematicsAPITests = [
        ("testInteger", testInteger),
        ("testRationalNumber", testRationalNumber),
        ("testWholeNumber", testWholeNumber),
    ]
}

extension SDGPrecisionMathematicsInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPrecisionMathematicsInternalTests = [
        ("testUIntHalvesView", testUIntHalvesView),
        ("testWholeNumberBinaryView", testWholeNumberBinaryView),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGPrecisionMathematicsAPITests.__allTests__SDGPrecisionMathematicsAPITests),
        testCase(SDGPrecisionMathematicsInternalTests.__allTests__SDGPrecisionMathematicsInternalTests),
    ]
}
#endif
