#if !canImport(ObjectiveC)
import XCTest

extension SDGPrecisionMathematicsAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPrecisionMathematicsAPITests = [
        ("testInteger", testInteger),
        ("testRationalNumber", testRationalNumber),
        ("testWholeNumber", testWholeNumber),
    ]
}

extension SDGPrecisionMathematicsInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGPrecisionMathematicsInternalTests = [
        ("testUIntHalvesView", testUIntHalvesView),
        ("testWholeNumberBinaryView", testWholeNumberBinaryView),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGPrecisionMathematicsAPITests.__allTests__SDGPrecisionMathematicsAPITests),
        testCase(SDGPrecisionMathematicsInternalTests.__allTests__SDGPrecisionMathematicsInternalTests),
    ]
}
#endif
