/*
 XCTestManifests.swift

 This source file is part of the SDGCornerstone open source project.
 https://sdggiesbrecht.github.io/SDGCornerstone

 Copyright ©2019 Jeremy David Giesbrecht and the SDGCornerstone project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

#if !canImport(ObjectiveC)
import XCTest

extension SDGLocalizationAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGLocalizationAPITests = [
        ("testAngle", testAngle),
        ("testBool", testBool),
        ("testCasing", testCasing),
        ("testCustomStringConvertible", testCustomStringConvertible),
        ("testLocalization", testLocalization),
        ("testLocalizationData", testLocalizationData),
        ("testLocalizationRelationships", testLocalizationRelationships),
        ("testLocalizationSetting", testLocalizationSetting),
        ("testRange", testRange),
        ("testRationalArithmetic", testRationalArithmetic),
        ("testStateData", testStateData),
        ("testUserFacingDynamicText", testUserFacingDynamicText),
        ("testWholeArithmetic", testWholeArithmetic),
    ]
}

extension SDGLocalizationInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGLocalizationInternalTests = [
        ("testContentLocalization", testContentLocalization),
        ("testInterfaceLocalization", testInterfaceLocalization),
        ("testLocalizationSetting", testLocalizationSetting),
        ("testWholeNumber", testWholeNumber),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGLocalizationAPITests.__allTests__SDGLocalizationAPITests),
        testCase(SDGLocalizationInternalTests.__allTests__SDGLocalizationInternalTests),
    ]
}
#endif
