#if !canImport(ObjectiveC)
import XCTest

extension SDGRandomizationAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGRandomizationAPITests = [
        ("testBool", testBool),
        ("testCollection", testCollection),
        ("testCyclicalNumberGenerator", testCyclicalNumberGenerator),
        ("testMeasurement", testMeasurement),
        ("testPseudorandomNumberGenerator", testPseudorandomNumberGenerator),
        ("testRangeReplaceableCollection", testRangeReplaceableCollection),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGRandomizationAPITests.__allTests__SDGRandomizationAPITests),
    ]
}
#endif
