#if !canImport(ObjectiveC)
import XCTest

extension SDGControlFlowAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGControlFlowAPITests = [
        ("testCaching", testCaching),
        ("testCodable", testCodable),
        ("testNonmutatingVariants", testNonmutatingVariants),
        ("testPerformanceTest", testPerformanceTest),
        ("testShared", testShared),
        ("testSharedProperty", testSharedProperty),
        ("testWeak", testWeak),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGControlFlowAPITests.__allTests__SDGControlFlowAPITests),
    ]
}
#endif
