#if !canImport(ObjectiveC)
import XCTest

extension SDGCalendarAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCalendarAPITests = [
        ("testCalendarComponent", testCalendarComponent),
        ("testCalendarDate", testCalendarDate),
        ("testCalendarInterval", testCalendarInterval),
        ("testGregorianDay", testGregorianDay),
        ("testGregorianHour", testGregorianHour),
        ("testGregorianMinute", testGregorianMinute),
        ("testGregorianMonth", testGregorianMonth),
        ("testGregorianSecond", testGregorianSecond),
        ("testGregorianWeekday", testGregorianWeekday),
        ("testGregorianYear", testGregorianYear),
        ("testHebrewDay", testHebrewDay),
        ("testHebrewHour", testHebrewHour),
        ("testHebrewMonth", testHebrewMonth),
        ("testHebrewMonthAndYear", testHebrewMonthAndYear),
        ("testHebrewPart", testHebrewPart),
        ("testHebrewWeekday", testHebrewWeekday),
        ("testHebrewYear", testHebrewYear),
        ("testWeekday", testWeekday),
    ]
}

extension SDGCalendarInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCalendarInternalTests = [
        ("testDate", testDate),
        ("testGregorianMonth", testGregorianMonth),
        ("testGregorianWeekdayDate", testGregorianWeekdayDate),
        ("testHebrewWeekdayDate", testHebrewWeekdayDate),
        ("testHebrewYear", testHebrewYear),
        ("testRelativeDate", testRelativeDate),
    ]
}

extension SDGCalendarRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCalendarRegressionTests = [
        ("testCalendarEquatability", testCalendarEquatability),
        ("testWeekday", testWeekday),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGCalendarAPITests.__allTests__SDGCalendarAPITests),
        testCase(SDGCalendarInternalTests.__allTests__SDGCalendarInternalTests),
        testCase(SDGCalendarRegressionTests.__allTests__SDGCalendarRegressionTests),
    ]
}
#endif
