#if !canImport(ObjectiveC)
import XCTest

extension SDGVersioningAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGVersioningAPITests = [
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGVersioningAPITests.__allTests__SDGVersioningAPITests),
    ]
}
#endif
