#if !canImport(ObjectiveC)
import XCTest

extension SDGLogicAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGLogicAPITests = [
        ("testAny", testAny),
        ("testBool", testBool),
        ("testEquatable", testEquatable),
        ("testOptional", testOptional),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGLogicAPITests.__allTests__SDGLogicAPITests),
    ]
}
#endif
