#if !canImport(ObjectiveC)
import XCTest

extension SDGConcurrencyAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGConcurrencyAPITests = [
        ("testRunLoop", testRunLoop),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGConcurrencyAPITests.__allTests__SDGConcurrencyAPITests),
    ]
}
#endif
