#if !canImport(ObjectiveC)
import XCTest

extension SDGTextAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGTextAPITests = [
        ("testCharacterSet", testCharacterSet),
        ("testFont", testFont),
        ("testLineView", testLineView),
        ("testLineViewIndex", testLineViewIndex),
        ("testNewlinePattern", testNewlinePattern),
        ("testRange", testRange),
        ("testScalarView", testScalarView),
        ("testSemanticMarkup", testSemanticMarkup),
        ("testStrictString", testStrictString),
        ("testStrictStringClusterView", testStrictStringClusterView),
        ("testString", testString),
        ("testStringClusterIndex", testStringClusterIndex),
        ("testStringFamily", testStringFamily),
        ("testStringScalarIndex", testStringScalarIndex),
        ("testStringScalarView", testStringScalarView),
        ("testUnicodeScalar", testUnicodeScalar),
    ]
}

extension SDGTextInternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGTextInternalTests = [
        ("testLineViewIndex", testLineViewIndex),
    ]
}

extension SDGTextRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGTextRegressionTests = [
        ("testLastLineNotDropped", testLastLineNotDropped),
        ("testMatchlessComponentSeperation", testMatchlessComponentSeperation),
        ("testMatchlessSearch", testMatchlessSearch),
        ("testNestingLevelLocation", testNestingLevelLocation),
        ("testReverseSearch", testReverseSearch),
        ("testSemanticMarkupToAttributedStringPreservesFont", testSemanticMarkupToAttributedStringPreservesFont),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGTextAPITests.__allTests__SDGTextAPITests),
        testCase(SDGTextInternalTests.__allTests__SDGTextInternalTests),
        testCase(SDGTextRegressionTests.__allTests__SDGTextRegressionTests),
    ]
}
#endif
