#if !canImport(ObjectiveC)
import XCTest

extension SDGCollectionsAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCollectionsAPITests = [
        ("testAbsoluteComplement", testAbsoluteComplement),
        ("testAddable", testAddable),
        ("testAlternativePatterns", testAlternativePatterns),
        ("testAnyPattern", testAnyPattern),
        ("testArray", testArray),
        ("testBidirectionalCollection", testBidirectionalCollection),
        ("testBijectiveMapping", testBijectiveMapping),
        ("testCollection", testCollection),
        ("testComparableSet", testComparableSet),
        ("testConcatenatedPatterns", testConcatenatedPatterns),
        ("testConditionalPattern", testConditionalPattern),
        ("testContextualMapping", testContextualMapping),
        ("testDictionary", testDictionary),
        ("testFiniteSet", testFiniteSet),
        ("testIntensionalSet", testIntensionalSet),
        ("testIntersection", testIntersection),
        ("testLiteralPattern", testLiteralPattern),
        ("testMutableSet", testMutableSet),
        ("testNegatedPattern", testNegatedPattern),
        ("testPatternClassCluster", testPatternClassCluster),
        ("testRange", testRange),
        ("testRangeReplaceableCollection", testRangeReplaceableCollection),
        ("testRepetitionPattern", testRepetitionPattern),
        ("testSet", testSet),
        ("testSetInRepresentableUniverse", testSetInRepresentableUniverse),
        ("testSymmetricDifference", testSymmetricDifference),
        ("testUnion", testUnion),
    ]
}

extension SDGCollectionsRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGCollectionsRegressionTests = [
        ("testBoundedRepetitionPatternSearch", testBoundedRepetitionPatternSearch),
        ("testTrailingConditionSearch", testTrailingConditionSearch),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGCollectionsAPITests.__allTests__SDGCollectionsAPITests),
        testCase(SDGCollectionsRegressionTests.__allTests__SDGCollectionsRegressionTests),
    ]
}
#endif
