#if !canImport(ObjectiveC)
import XCTest

extension SDGGeometryAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGGeometryAPITests = [
        ("testAngle", testAngle),
        ("testBézierPath", testBézierPath),
        ("testPoint", testPoint),
        ("testVector", testVector),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGGeometryAPITests.__allTests__SDGGeometryAPITests),
    ]
}
#endif
