#if !canImport(ObjectiveC)
import XCTest

extension SDGExternalProcessAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGExternalProcessAPITests = [
        ("testExternalProcess", testExternalProcess),
        ("testExternalProcessError", testExternalProcessError),
        ("testShell", testShell),
    ]
}

extension SDGExternalProcessRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGExternalProcessRegressionTests = [
        ("testDelayedShellOutput", testDelayedShellOutput),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGExternalProcessAPITests.__allTests__SDGExternalProcessAPITests),
        testCase(SDGExternalProcessRegressionTests.__allTests__SDGExternalProcessRegressionTests),
    ]
}
#endif
