# Swift 5.5 Ubuntu.yaml
#
# This source file is part of the SDGCornerstone open source project.
# https://sdggiesbrecht.github.io/SDGCornerstone
#
# Copyright ©2021 Jeremy David Giesbrecht and the SDGCornerstone project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.5 Ubuntu

on: [push, pull_request]

jobs:
  Swift_5_5_Ubuntu:
    name: Swift 5.5 Ubuntu
    runs-on: ubuntu-20.04
    container: swift:5.5.0-focal
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: Ubuntu‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            libncurses-dev \
            libsqlite3-dev
    - name: Install Workspace dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            curl
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
    - name: Grant permission to cache
      shell: bash
      run: |
        set -x
        chmod -R a+rwx .
