# Swift 5.5 tvOS.yaml
#
# This source file is part of the SDGCornerstone open source project.
# https://sdggiesbrecht.github.io/SDGCornerstone
#
# Copyright ©2021 Jeremy David Giesbrecht and the SDGCornerstone project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.5 tvOS

on: [push, pull_request]

jobs:
  Swift_5_5_tvOS:
    name: Swift 5.5 tvOS
    runs-on: macos-11
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: macOS‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Set Xcode up
      shell: bash
      run: |
        set -x
        sudo xcode-select -switch /Applications/Xcode_13.0.app
        xcodebuild -version
        swift --version
    - name: Validate
      shell: bash
      run: |
        set -x
        export TARGETING_TVOS=true
        xcodebuild test -destination 'name=Apple TV 4K (2nd generation)' -scheme SDGCornerstone-Package
