# CentOS.yaml
#
# This source file is part of the SDGCornerstone open source project.
# https://sdggiesbrecht.github.io/SDGCornerstone
#
# Copyright ©2021 Jeremy David Giesbrecht and the SDGCornerstone project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.5 CentOS

on: [push, pull_request]

jobs:
  Swift_5_5_CentOS:
    name: Swift 5.5 CentOS
    runs-on: ubuntu-20.04
    container: swift:5.5.0-centos8
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: CentOS‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        yum install --assumeyes \
          ncurses-devel \
          sqlite-devel
    - name: Install Workspace dependencies
      shell: bash
      run: |
        set -x
        yum install --assumeyes \
          curl
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
    - name: Grant permission to cache
      shell: bash
      run: |
        set -x
        chmod -R a+rwx .
