#if !canImport(ObjectiveC)
import XCTest

extension SDGBinaryDataAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGBinaryDataAPITests = [
        ("testData", testData),
        ("testDataStream", testDataStream),
        ("testUInt", testUInt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGBinaryDataAPITests.__allTests__SDGBinaryDataAPITests),
    ]
}
#endif
